# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "Microsoft.Identity*"
    ignore:
        # We do not want this leaving 5.5.0 since we don't use it and it could break customers
      - dependency-name: "Microsoft.IdentityModel.Protocols.WsFederation"
    labels:
      - "dependabot"
      - "dependencies"
    groups:
      # Groups all recommended minor and patch updates with a security designation into a single PR
      security:
        applies-to: security-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      # Groups all minor and patch non-security designated version updates into a single PR
      notsecurity:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
      # Separate group for ASP.NET dependencies
      aspnet:
        patterns:
          - "Microsoft.AspNetCore.*"
      # Separate group for Microsoft.Extensions dependencies
      microsoft-extensions:
        patterns:
          - "Microsoft.Extensions.*"
