trigger:
- master

pr:
  autoCancel: true
  branches:
    include:
      - master

jobs:
- job: "PR_build"
  pool:
    vmImage: 'windows-2022'
    demands:
    - msbuild
    - visualstudio
  steps:
    - template: build/template-install-dependencies.yaml
    - template: build/template-run-unit-tests.yaml
