# This docker file is used for building the container image from a published set of files.
# This is used when for workflows where the files need to be signed in CI/CD.

FROM mcr.microsoft.com/dotnet/aspnet:9.0-nanoserver-ltsc2022 AS base
WORKDIR /app

COPY app/publish .
USER app
ENTRYPOINT ["dotnet", "Microsoft.Identity.Web.Sidecar.dll"]
