@Microsoft.Identity.Web.Sidecar_HostAddress = http://localhost:5178

@AccessToken =
@ApiName = 

###

GET {{Microsoft.Identity.Web.Sidecar_HostAddress}}/openapi/v1.json

###

GET {{Microsoft.Identity.Web.Sidecar_HostAddress}}/Validate
Authorization: Bearer {{AccessToken}}

###

GET {{Microsoft.Identity.Web.Sidecar_HostAddress}}/AuthorizationHeader/{{ApiName}}
Authorization: Bearer {{AccessToken}}

###

Get {{Microsoft.Identity.Web.Sidecar_HostAddress}}/AuthorizationHeaderUnauthenticated/{{ApiName}}

###

GET {{Microsoft.Identity.Web.Sidecar_HostAddress}}/AuthorizationHeader/{{ApiName}}?optionsOverride.Scopes=User.Read&optionsOverride.AcquireTokenOptions.Tenant=f645ad92-e38d-4d1a-b510-d1b09a74a8ca
Authorization: Bearer {{AccessToken}}

###

POST {{Microsoft.Identity.Web.Sidecar_HostAddress}}/DownstreamApi/{{ApiName}}
Accept: application/json
Authorization: Bearer {{AccessToken}}

###

POST {{Microsoft.Identity.Web.Sidecar_HostAddress}}/DownstreamApiUnauthenticated/{{ApiName}}
Accept: application/json
