# coding: utf-8

# flake8: noqa
"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.authorization_header_result import AuthorizationHeaderResult
from openapi_client.models.downstream_api_result import DownstreamApiResult
from openapi_client.models.problem_details import ProblemDetails
from openapi_client.models.validate_authorization_header_result import ValidateAuthorizationHeaderResult

