# coding: utf-8

"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr
from typing import Optional
from typing_extensions import Annotated
from openapi_client.models.downstream_api_result import DownstreamApiResult
from openapi_client.models.true_bypass_token_cache import TrueBypassTokenCache

from openapi_client.api_client import ApiClient, RequestSerialized
from openapi_client.api_response import ApiResponse
from openapi_client.rest import RESTResponseType


class DownstreamApiEndpointApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def downstream_api(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> DownstreamApiResult:
        """Invoke a configured downstream API through the sidecar using the authenticated identity.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def downstream_api_with_http_info(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[DownstreamApiResult]:
        """Invoke a configured downstream API through the sidecar using the authenticated identity.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def downstream_api_without_preload_content(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Invoke a configured downstream API through the sidecar using the authenticated identity.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _downstream_api_serialize(
        self,
        api_name,
        agent_identity,
        agent_username,
        options_override_scopes,
        options_override_request_app_token,
        options_override_base_url,
        options_override_relative_path,
        options_override_http_method,
        options_override_accept_header,
        options_override_content_type,
        options_override_acquire_token_options_tenant,
        options_override_acquire_token_options_force_refresh,
        options_override_acquire_token_options_claims,
        options_override_acquire_token_options_correlation_id,
        options_override_acquire_token_options_long_running_web_api_session_key,
        options_override_acquire_token_options_fmi_path,
        options_override_acquire_token_options_pop_public_key,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if api_name is not None:
            _path_params['apiName'] = api_name
        # process the query parameters
        if agent_identity is not None:
            
            _query_params.append(('AgentIdentity', agent_identity))
            
        if agent_username is not None:
            
            _query_params.append(('AgentUsername', agent_username))
            
        if options_override_scopes is not None:
            
            _query_params.append(('optionsOverride.Scopes', options_override_scopes))
            
        if options_override_request_app_token is not None:
            
            _query_params.append(('optionsOverride.RequestAppToken', options_override_request_app_token))
            
        if options_override_base_url is not None:
            
            _query_params.append(('optionsOverride.BaseUrl', options_override_base_url))
            
        if options_override_relative_path is not None:
            
            _query_params.append(('optionsOverride.RelativePath', options_override_relative_path))
            
        if options_override_http_method is not None:
            
            _query_params.append(('optionsOverride.HttpMethod', options_override_http_method))
            
        if options_override_accept_header is not None:
            
            _query_params.append(('optionsOverride.AcceptHeader', options_override_accept_header))
            
        if options_override_content_type is not None:
            
            _query_params.append(('optionsOverride.ContentType', options_override_content_type))
            
        if options_override_acquire_token_options_tenant is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.Tenant', options_override_acquire_token_options_tenant))
            
        if options_override_acquire_token_options_force_refresh is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.ForceRefresh', options_override_acquire_token_options_force_refresh))
            
        if options_override_acquire_token_options_claims is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.Claims', options_override_acquire_token_options_claims))
            
        if options_override_acquire_token_options_correlation_id is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.CorrelationId', options_override_acquire_token_options_correlation_id))
            
        if options_override_acquire_token_options_long_running_web_api_session_key is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.LongRunningWebApiSessionKey', options_override_acquire_token_options_long_running_web_api_session_key))
            
        if options_override_acquire_token_options_fmi_path is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.FmiPath', options_override_acquire_token_options_fmi_path))
            
        if options_override_acquire_token_options_pop_public_key is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.PopPublicKey', options_override_acquire_token_options_pop_public_key))
            
        if options_override_acquire_token_options_managed_identity_user_assigned_client_id is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.ManagedIdentity.UserAssignedClientId', options_override_acquire_token_options_managed_identity_user_assigned_client_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/DownstreamApi/{apiName}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def downstream_api_unauthenticated(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> DownstreamApiResult:
        """Invoke a configured downstream API through the sidecar using the configured client credentials.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_unauthenticated_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def downstream_api_unauthenticated_with_http_info(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[DownstreamApiResult]:
        """Invoke a configured downstream API through the sidecar using the configured client credentials.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_unauthenticated_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def downstream_api_unauthenticated_without_preload_content(
        self,
        api_name: StrictStr,
        agent_identity: Optional[StrictStr] = None,
        agent_username: Optional[StrictStr] = None,
        options_override_scopes: Annotated[Optional[StrictStr], Field(description="Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read")] = None,
        options_override_request_app_token: Annotated[Optional[StrictBool], Field(description="true = acquire an app (client credentials) token instead of user token.")] = None,
        options_override_base_url: Annotated[Optional[StrictStr], Field(description="Override downstream API base URL.")] = None,
        options_override_relative_path: Annotated[Optional[StrictStr], Field(description="Override relative path appended to BaseUrl.")] = None,
        options_override_http_method: Annotated[Optional[StrictStr], Field(description="Override HTTP method (GET, POST, PATCH, etc.).")] = None,
        options_override_accept_header: Annotated[Optional[StrictStr], Field(description="Sets Accept header (e.g. application/json).")] = None,
        options_override_content_type: Annotated[Optional[StrictStr], Field(description="Sets Content-Type used for serialized body (if body provided).")] = None,
        options_override_acquire_token_options_tenant: Annotated[Optional[StrictStr], Field(description="Override tenant (GUID or 'common').")] = None,
        options_override_acquire_token_options_force_refresh: Annotated[Optional[TrueBypassTokenCache], Field(description="boolean")] = None,
        options_override_acquire_token_options_claims: Annotated[Optional[StrictStr], Field(description="JSON claims challenge or extra claims.")] = None,
        options_override_acquire_token_options_correlation_id: Annotated[Optional[StrictStr], Field(description="GUID correlation id for token acquisition.")] = None,
        options_override_acquire_token_options_long_running_web_api_session_key: Annotated[Optional[StrictStr], Field(description="Session key for long running OBO flows.")] = None,
        options_override_acquire_token_options_fmi_path: Annotated[Optional[StrictStr], Field(description="Federated Managed Identity path (if using FMI).")] = None,
        options_override_acquire_token_options_pop_public_key: Annotated[Optional[StrictStr], Field(description="Public key or JWK for PoP / AT-POP requests.")] = None,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id: Annotated[Optional[StrictStr], Field(description="Managed Identity client id (user-assigned).")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Invoke a configured downstream API through the sidecar using the configured client credentials.

        Override downstream call options using dotted query parameters prefixed with 'optionsOverride.'. Examples:   ?optionsOverride.Scopes=User.Read   ?optionsOverride.Scopes=User.Read&optionsOverride.Scopes=Mail.Read   ?optionsOverride.AcquireTokenOptions.Tenant=GUID   ?optionsOverride.RequestAppToken=true&optionsOverride.Scopes=https://graph.microsoft.com/.default

        :param api_name: (required)
        :type api_name: str
        :param agent_identity:
        :type agent_identity: str
        :param agent_username:
        :type agent_username: str
        :param options_override_scopes: Repeatable. Each occurrence adds one scope. Example: optionsOverride.Scopes=User.Read
        :type options_override_scopes: str
        :param options_override_request_app_token: true = acquire an app (client credentials) token instead of user token.
        :type options_override_request_app_token: bool
        :param options_override_base_url: Override downstream API base URL.
        :type options_override_base_url: str
        :param options_override_relative_path: Override relative path appended to BaseUrl.
        :type options_override_relative_path: str
        :param options_override_http_method: Override HTTP method (GET, POST, PATCH, etc.).
        :type options_override_http_method: str
        :param options_override_accept_header: Sets Accept header (e.g. application/json).
        :type options_override_accept_header: str
        :param options_override_content_type: Sets Content-Type used for serialized body (if body provided).
        :type options_override_content_type: str
        :param options_override_acquire_token_options_tenant: Override tenant (GUID or 'common').
        :type options_override_acquire_token_options_tenant: str
        :param options_override_acquire_token_options_force_refresh: boolean
        :type options_override_acquire_token_options_force_refresh: TrueBypassTokenCache
        :param options_override_acquire_token_options_claims: JSON claims challenge or extra claims.
        :type options_override_acquire_token_options_claims: str
        :param options_override_acquire_token_options_correlation_id: GUID correlation id for token acquisition.
        :type options_override_acquire_token_options_correlation_id: str
        :param options_override_acquire_token_options_long_running_web_api_session_key: Session key for long running OBO flows.
        :type options_override_acquire_token_options_long_running_web_api_session_key: str
        :param options_override_acquire_token_options_fmi_path: Federated Managed Identity path (if using FMI).
        :type options_override_acquire_token_options_fmi_path: str
        :param options_override_acquire_token_options_pop_public_key: Public key or JWK for PoP / AT-POP requests.
        :type options_override_acquire_token_options_pop_public_key: str
        :param options_override_acquire_token_options_managed_identity_user_assigned_client_id: Managed Identity client id (user-assigned).
        :type options_override_acquire_token_options_managed_identity_user_assigned_client_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._downstream_api_unauthenticated_serialize(
            api_name=api_name,
            agent_identity=agent_identity,
            agent_username=agent_username,
            options_override_scopes=options_override_scopes,
            options_override_request_app_token=options_override_request_app_token,
            options_override_base_url=options_override_base_url,
            options_override_relative_path=options_override_relative_path,
            options_override_http_method=options_override_http_method,
            options_override_accept_header=options_override_accept_header,
            options_override_content_type=options_override_content_type,
            options_override_acquire_token_options_tenant=options_override_acquire_token_options_tenant,
            options_override_acquire_token_options_force_refresh=options_override_acquire_token_options_force_refresh,
            options_override_acquire_token_options_claims=options_override_acquire_token_options_claims,
            options_override_acquire_token_options_correlation_id=options_override_acquire_token_options_correlation_id,
            options_override_acquire_token_options_long_running_web_api_session_key=options_override_acquire_token_options_long_running_web_api_session_key,
            options_override_acquire_token_options_fmi_path=options_override_acquire_token_options_fmi_path,
            options_override_acquire_token_options_pop_public_key=options_override_acquire_token_options_pop_public_key,
            options_override_acquire_token_options_managed_identity_user_assigned_client_id=options_override_acquire_token_options_managed_identity_user_assigned_client_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DownstreamApiResult",
            '400': "ProblemDetails",
            '401': "ProblemDetails",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _downstream_api_unauthenticated_serialize(
        self,
        api_name,
        agent_identity,
        agent_username,
        options_override_scopes,
        options_override_request_app_token,
        options_override_base_url,
        options_override_relative_path,
        options_override_http_method,
        options_override_accept_header,
        options_override_content_type,
        options_override_acquire_token_options_tenant,
        options_override_acquire_token_options_force_refresh,
        options_override_acquire_token_options_claims,
        options_override_acquire_token_options_correlation_id,
        options_override_acquire_token_options_long_running_web_api_session_key,
        options_override_acquire_token_options_fmi_path,
        options_override_acquire_token_options_pop_public_key,
        options_override_acquire_token_options_managed_identity_user_assigned_client_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if api_name is not None:
            _path_params['apiName'] = api_name
        # process the query parameters
        if agent_identity is not None:
            
            _query_params.append(('AgentIdentity', agent_identity))
            
        if agent_username is not None:
            
            _query_params.append(('AgentUsername', agent_username))
            
        if options_override_scopes is not None:
            
            _query_params.append(('optionsOverride.Scopes', options_override_scopes))
            
        if options_override_request_app_token is not None:
            
            _query_params.append(('optionsOverride.RequestAppToken', options_override_request_app_token))
            
        if options_override_base_url is not None:
            
            _query_params.append(('optionsOverride.BaseUrl', options_override_base_url))
            
        if options_override_relative_path is not None:
            
            _query_params.append(('optionsOverride.RelativePath', options_override_relative_path))
            
        if options_override_http_method is not None:
            
            _query_params.append(('optionsOverride.HttpMethod', options_override_http_method))
            
        if options_override_accept_header is not None:
            
            _query_params.append(('optionsOverride.AcceptHeader', options_override_accept_header))
            
        if options_override_content_type is not None:
            
            _query_params.append(('optionsOverride.ContentType', options_override_content_type))
            
        if options_override_acquire_token_options_tenant is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.Tenant', options_override_acquire_token_options_tenant))
            
        if options_override_acquire_token_options_force_refresh is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.ForceRefresh', options_override_acquire_token_options_force_refresh))
            
        if options_override_acquire_token_options_claims is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.Claims', options_override_acquire_token_options_claims))
            
        if options_override_acquire_token_options_correlation_id is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.CorrelationId', options_override_acquire_token_options_correlation_id))
            
        if options_override_acquire_token_options_long_running_web_api_session_key is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.LongRunningWebApiSessionKey', options_override_acquire_token_options_long_running_web_api_session_key))
            
        if options_override_acquire_token_options_fmi_path is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.FmiPath', options_override_acquire_token_options_fmi_path))
            
        if options_override_acquire_token_options_pop_public_key is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.PopPublicKey', options_override_acquire_token_options_pop_public_key))
            
        if options_override_acquire_token_options_managed_identity_user_assigned_client_id is not None:
            
            _query_params.append(('optionsOverride.AcquireTokenOptions.ManagedIdentity.UserAssignedClientId', options_override_acquire_token_options_managed_identity_user_assigned_client_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/problem+json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/DownstreamApiUnauthenticated/{apiName}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


