# This issue template is for use in opening issues that document Ask Mode Changes, for features or changes that come after the release candidate deadline.

name: "Microsoft.Identity.Web Ask Mode Change"
description: Request an exception to release a feature or add any changes after the release candidate deadline, excludes fixes for preview regressions.
title: "[Ask Mode Change]: "
labels: "Ask Mode Change"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the feature.
    validations:
      required: true
  - type: input
    id: release-date
    attributes:
      label: Date
      description: Which release date are you targeting?
    validations:
      required: true
  - type: dropdown
    id: version-bump
    attributes:
      label: Type of version bump
      description: Indicate if this feature would incur a major, minor, or patch version bump. 
      options:
        - label: "Major"
        - label: "Minor"
        - label: "Patch"
        - label: "Not sure"
    validations:
      required: true
  - type: checkboxes
    id: other-libraries
    attributes:
      label: Other libraries
      description: Does this feature release rely on the release of any other ID4S libraries?
      options:
        - label: "Yes"
        - label: "No"
    validations:
      required: true
  - type: checkboxes
    id: if-relies-on-other-libraries
    attributes:
      label: If you answered "yes" to the previous question, please indicate which libraries.
      description: Check the boxes of the other ID4S libraries to be released.
      options:
        - label: Microsoft.Identity.Abstractions
        - label: Microsoft.IdentityModel
  - type: textarea
    id: reason
    attributes:
      label: Reason for exception
      description: Please explain why the feature release can't wait until the next month.
    validations:
      required: true
  - type: textarea
    id: testing-attestation
    attributes:
      label: Testing attestation
      description: Describe the testing and validation that was conducted for this feature. Include links to test coverage, proof of partner validation, etc.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Notify the Release V-Team
      description: After submitting this issue, you agree to notify the release v-team. 
      options:
        - label: I agree.
          required: true
 