# coding: utf-8

"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authorization_header_endpoint_api import AuthorizationHeaderEndpointApi


class TestAuthorizationHeaderEndpointApi(unittest.TestCase):
    """AuthorizationHeaderEndpointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthorizationHeaderEndpointApi()

    def tearDown(self) -> None:
        pass

    def test_authorization_header(self) -> None:
        """Test case for authorization_header

        Get an authorization header for a configured downstream API.
        """
        pass

    def test_authorization_header_unauthenticated(self) -> None:
        """Test case for authorization_header_unauthenticated

        Get an authorization header for a configured downstream API using this configured client credentials.
        """
        pass


if __name__ == '__main__':
    unittest.main()
