# coding: utf-8

"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.downstream_api_endpoint_api import DownstreamApiEndpointApi


class TestDownstreamApiEndpointApi(unittest.TestCase):
    """DownstreamApiEndpointApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DownstreamApiEndpointApi()

    def tearDown(self) -> None:
        pass

    def test_downstream_api(self) -> None:
        """Test case for downstream_api

        Invoke a configured downstream API through the sidecar using the authenticated identity.
        """
        pass

    def test_downstream_api_unauthenticated(self) -> None:
        """Test case for downstream_api_unauthenticated

        Invoke a configured downstream API through the sidecar using the configured client credentials.
        """
        pass


if __name__ == '__main__':
    unittest.main()
