# coding: utf-8

"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.validate_request_endpoints_api import ValidateRequestEndpointsApi


class TestValidateRequestEndpointsApi(unittest.TestCase):
    """ValidateRequestEndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidateRequestEndpointsApi()

    def tearDown(self) -> None:
        pass

    def test_validate_authorization_header(self) -> None:
        """Test case for validate_authorization_header

        """
        pass


if __name__ == '__main__':
    unittest.main()
