// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClientInfoTests.DeserializeFromJson_NullOrEmptyJsonByteArray_ReturnsNull")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebApiExtensionsTests.AddProtectedWebApiCallsProtectedWebApi_WithConfigName")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_AadEmptyTenantId_ReturnsNull")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_AadInstanceWithTrailingSlash_ReturnsValidAadAuthority")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_AadValidOptions_ReturnsValidAadAuthority")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_B2CEmptyDomain_ReturnsNull")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_B2CValidOptions_ReturnsValidB2CAuthority")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.AuthorityHelpersTests.BuildAuthority_EmptyInstance_ReturnsNull")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetDisplayName_WithSomeOrAllNameClaims_ReturnsName")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetDomainHint_WithTenantIdClaims_ReturnsDomainHint")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetLoginHint_WithSomeOrAllNameClaims_ReturnsName")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetMsalAccountId_WithNeededClaims_ReturnsFormattedMsalId")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetNameIdentifierId_WithUtidClaim_ReturnsNameId")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetObjectId_WithOidOrObjectIdClaims_ReturnsObjectId")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetTenantId_WithTidOrTenantIdClaims_ReturnsTenantId")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.ClaimsPrincipalExtensionsTests.GetUserFlowId_WithTfpOrUserFlowClaims_ReturnsUserFlowId")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.CookiePolicyOptionsExtensionsTests.#ctor")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.InstanceDiscovery.IssuerConfigurationRetrieverTests.MakeIssuerMetadata~Microsoft.Identity.Web.InstanceDiscovery.IssuerMetadata")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.MicrosoftIdentityOptionsTests.IsB2C_NotNullOrEmptyUserFlow_ReturnsTrue")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_FromB2CAuthority_InvalidIssuer_Fails")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_FromB2CAuthority_InvalidIssuerTid_Fails")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_FromB2CAuthority_WithNoTidClaim_ValidateSuccessfully")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_FromB2CAuthority_WithTidClaim_ValidateSuccessfully")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_FromCustomB2CAuthority_ValidateSuccessfully")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.Resource.AadIssuerValidatorTests.Validate_NotMatchedToMultipleIssuers_ThrowsException")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebApiExtensionsTests.AddProtectedWebApi_TestJwtBearerTokenValidatedEvent(Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerOptions,System.Func{Microsoft.AspNetCore.Authentication.JwtBearer.TokenValidatedContext,System.Threading.Tasks.Task})")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebApiExtensionsTests.EnsureAuthorityIsV2_0(System.String,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebApiExtensionsTests.EnsureValidAudiencesContainsApiGuidIfGuidProvided(System.String,System.String[],System.String[])")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebApiExtensionsTests.GetConfigSection(System.String)~Microsoft.Extensions.Configuration.IConfigurationSection")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "not applicable", Scope = "member", Target = "~M:Microsoft.Identity.Web.Test.WebAppExtensionsTests.EnsureAuthorityIsV2_0(System.String,System.String)")]
