# coding: utf-8

# flake8: noqa

"""
    Microsoft.Identity.Web.Sidecar | v1

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AuthorizationHeaderEndpointApi",
    "DownstreamApiEndpointApi",
    "ValidateRequestEndpointsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthorizationHeaderResult",
    "DownstreamApiResult",
    "ProblemDetails",
    "ValidateAuthorizationHeaderResult",
]

# import apis into sdk package
from openapi_client.api.authorization_header_endpoint_api import AuthorizationHeaderEndpointApi as AuthorizationHeaderEndpointApi
from openapi_client.api.downstream_api_endpoint_api import DownstreamApiEndpointApi as DownstreamApiEndpointApi
from openapi_client.api.validate_request_endpoints_api import ValidateRequestEndpointsApi as ValidateRequestEndpointsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.authorization_header_result import AuthorizationHeaderResult as AuthorizationHeaderResult
from openapi_client.models.downstream_api_result import DownstreamApiResult as DownstreamApiResult
from openapi_client.models.problem_details import ProblemDetails as ProblemDetails
from openapi_client.models.validate_authorization_header_result import ValidateAuthorizationHeaderResult as ValidateAuthorizationHeaderResult

