name: "AOT Check"

on:
  push:
    branches: [ "master", "rel/v2" ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches: [ "master", "rel/v2" ]

env:
  TargetNetNext: True

jobs:
  analyze:
    runs-on: windows-latest
    name: AOT check

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET 10.0.x preview
      if: env.TargetNetNext == 'True'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Runs AOT check with .NET 9.0
      id: aot-powershell-net9
      run: build\test-aot.ps1 'net9.0'

    - name: Runs AOT check with .NET 10.0
      id: aot-powershell-net10
      if: env.TargetNetNext == 'True'
      run: build\test-aot.ps1 'net10.0'
      continue-on-error: true

