name: Run benchmark
on:
  workflow_dispatch: # Allows manual triggering of workflow
  push:
    branches:
      - master

permissions:
  # Deployments permission to deploy GitHub pages website
  deployments: write
  # Contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    env:
      AzureAd__ClientCredentials__0__SourceType: "ClientSecret"
      AzureAd__ClientCredentials__0__ClientSecret: ${{secrets.ClientSecret}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Run benchmark
        run: cd benchmark && dotnet run -c release -f net9.0 --filter 'Benchmarks.TokenAcquisitionBenchmark.*' --exporters json 

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store TokenAcquisitionBenchmark benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: TokenAcquisitionBenchmarks
          tool: 'benchmarkdotnet'
          output-file-path: benchmark/BenchmarkDotNet.Artifacts/results/Benchmarks.TokenAcquisitionBenchmark-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
          summary-always: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: benchmarks
